### ISSUE TITLE
Fix failing Helm Chart releases

### ISSUE THREAD

**Issue by MantisClone** [RequestNetwork/request-helm-charts#30]
# Problem

The automated "new version" Helm Chart releases are failing.
Reference: https://github.com/RequestNetwork/request-helm-charts/actions/workflows/new-version.yaml
Example: https://github.com/RequestNetwork/request-helm-charts/actions/runs/10024248949

**Comment by MantisClone** [comment]
@alexandre-abrioux Is this affecting Request Finance?

**Comment by alexandre-abrioux** [comment]
@MantisClone this should fix it: https://github.com/RequestNetwork/request-helm-charts/pull/31
